const RestaurantsPageActionsConstants = {
    ON_SORT_CHANGE: 'ON_SORT_CHANGE',
    GET_RESTAURANTS: 'GET_RESTAURANTS',
    GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
    SEARCH_RESTAURANTS_SUCCESS: 'SEARCH_RESTAURANTS_SUCCESS',
    GET_RESTAURANTS_FAILURE: 'GET_RESTAURANTS_FAILURE',
    CHANGE_LAYOUT: 'CHANGE_LAYOUT',
    CHANGE_VISIBILITY_RESTAURANT: 'CHANGE_VISIBILITY_RESTAURANT',
    CHANGE_VISIBILITY_REVIEW: 'CHANGE_VISIBILITY_REVIEW',
    SELECT_RESTAURANT: 'SELECT_RESTAURANT',
    SELECT_REVIEW: 'SELECT_REVIEW',
    CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',
    ADD_RATE: 'ADD_RATE',
    ADD_REVIEW_SUCCESS: 'ADD_REVIEW_SUCCESS',
    ADD_REVIEW_FAILURE: 'ADD_REVIEW_FAILURE',
    CHANGE_RATE: 'CHANGE_RATE',
    FILTER_NAMES: 'FILTER_NAMES',
    FILTER_LOCATIONS: 'FILTER_LOCATIONS',
    CHANGE_FILTER_NAMES: 'CHANGE_FILTER_NAMES',
    CHANGE_FILTER_LOCATIONS: 'CHANGE_FILTER_LOCATIONS',
    CHANGE_SCALE: 'CHANGE_SCALE',
    SEARCH_RESTAURANT: 'SEARCH_RESTAURANT'
};

const RatesConstants = {
    BATHROOM_QUALITY: 'bathroomQuality',
    STAFF_KINDNESS: 'staffKindness',
    CLEANLINESS: 'cleanliness',
    DRIVE_THRU_QUALITY: 'driveThruQuality',
    DELIVERY_SPEED: 'deliverySpeed',
    FOOD_QUALITY: 'foodQuality',
};

export {RestaurantsPageActionsConstants, RatesConstants}
