const RestaurantsPageActionsConstants = {
    ON_SORT_CHANGE: 'ON_SORT_CHANGE',
    GET_RESTAURANTS: 'GET_RESTAURANTS',
    GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
    GET_RESTAURANTS_FAILURE: 'GET_RESTAURANTS_FAILURE',
    CHANGE_LAYOUT: 'CHANGE_LAYOUT',
    CHANGE_VISIBILITY_RESTAURANT: 'CHANGE_VISIBILITY_RESTAURANT',
    CHANGE_VISIBILITY_REVIEW: 'CHANGE_VISIBILITY_REVIEW',
    SELECT_RESTAURANT: 'SELECT_RESTAURANT',
    SELECT_REVIEW: 'SELECT_REVIEW'
};

export {RestaurantsPageActionsConstants}