const RestaurantsPageActionsConstants = {
    ON_SORT_CHANGE: 'ON_SORT_CHANGE',
    GET_RESTAURANTS: 'GET_RESTAURANTS',
    GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
    GET_RESTAURANTS_FAILURE: 'GET_RESTAURANTS_FAILURE',
    CHANGE_LAYOUT: 'CHANGE_LAYOUT',
    CHANGE_VISIBILITY_RESTAURANT: 'CHANGE_VISIBILITY_RESTAURANT',
    CHANGE_VISIBILITY_REVIEW: 'CHANGE_VISIBILITY_REVIEW',
    SELECT_RESTAURANT: 'SELECT_RESTAURANT',
    SELECT_REVIEW: 'SELECT_REVIEW',
    CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',
    ADD_RATE: 'ADD_RATE',
    ADD_REVIEW_SUCCESS: 'ADD_REVIEW_SUCCESS',
    ADD_REVIEW_FAILURE: 'ADD_REVIEW_FAILURE',
    SELECT_RATE: 'SELECT_RATE'
};

export {RestaurantsPageActionsConstants}