const ProfileActionsConstants = {
    CHANGE_PROFILE_FIELD: 'CHANGE_PROFILE_FIELD',
    TOGGLE_EDIT: 'TOGGLE_EDIT',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    GET_USER_REVIEWS: 'GET_USER_REVIEWS',
    GET_USER_REVIEWS_SUCCESS: 'GET_USER_REVIEWS_SUCCESS',
    GET_USER_REVIEWS_FAILURE: 'GET_USER_REVIEWS_FAILURE'

};

export {ProfileActionsConstants}