const ProfileActionsConstants = {
    CHANGE_PROFILE_FIELD: 'CHANGE_PROFILE_FIELD',
    TOGGLE_EDIT: 'TOGGLE_EDIT',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    GET_USER_REVIEWS: 'GET_USER_REVIEWS',
    GET_USER_REVIEWS_SUCCESS: 'GET_USER_REVIEWS_SUCCESS',
    GET_USER_REVIEWS_FAILURE: 'GET_USER_REVIEWS_FAILURE',
    CHANGE_VISIBILITY_MY_REVIEWS: 'CHANGE_VISIBILITY_MY_REVIEWS',
    CHANGE_REVIEWS_LAYOUT: 'CHANGE_REVIEWS_LAYOUT',
    SELECT_MY_REVIEWS: 'SELECT_MY_REVIEWS',

};

const EditReviewActionsConstats = {
    EDIT_MY_REVIEWS: 'EDIT_MY_REVIEWS',
    EDIT_MY_REVIEWS_SUCCESS: 'EDIT_MY_REVIEWS_SUCCESS',
    EDIT_MY_REVIEWS_FAILURE: 'EDIT_MY_REVIEWS_FAILURE',
    DELETE_REVIEW: 'DELETE_REVIEW',
    DELETE_REVIEW_SUCCESS: 'DELETE_REVIEW_SUCCESS',
    DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE',
    GET_RESTAURANT_NAME: 'GET_RESTAURANT_NAME',
    GET_RESTAURANT_NAME_SUCCESS: 'GET_RESTAURANT_NAME_SUCCESS',
    GET_RESTAURANT_NAME_FAILIRE: 'GET_RESTAURANT_NAME_FAILURE',
    EDIT_MY_REVIEWS_WITH_PICTURES: 'EDIT_MY_REVIEWS_WITH_PICTURES',
    EDIT_MY_REVIEWS_WITH_PICTURES_SUCCESS: 'EDIT_MY_REVIEWS_WITH_PICTURES_SUCCESS',
    EDIT_MY_REVIEWS_WITH_PICTURES_FAILIRE: 'EDIT_MY_REVIEWS_WITH_PICTURES_FAILIRE',
    UPDATE_AVG: 'UPDATE_AVG',
    UPDATE_AVG_SUCCESS: 'UPDATE_AVG_SUCCESS',
    UPDATE_AVG_FAILIRE: 'UPDATE_AVG_FAILIRE'

}

const EditPictureActionsConstats = {
    EDIT_PICTURE_ON_DROP: 'EDIT_PICTURE_ON_DROP'

}

export {ProfileActionsConstants, EditReviewActionsConstats, EditPictureActionsConstats}