const ProfileActionsConstants = {
    CHANGE_PROFILE_FIELD: 'CHANGE_PROFILE_FIELD',
    TOGGLE_EDIT: 'TOGGLE_EDIT',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    GET_USER_REVIEWS: 'GET_USER_REVIEWS',
    GET_USER_REVIEWS_SUCCESS: 'GET_USER_REVIEWS_SUCCESS',
<<<<<<< HEAD
    GET_USER_REVIEWS_FAILURE: 'GET_USER_REVIEWS_FAILURE',
    CHANGE_VISIBILITY_MY_REVIEWS: 'CHANGE_VISIBILITY_MY_REVIEWS',
    CHANGE_REVIEWS_LAYOUT: 'CHANGE_REVIEWS_LAYOUT',
    SELECT_MY_REVIEWS: 'SELECT_MY_REVIEWS',

=======
    GET_USER_REVIEWS_FAILURE: 'GET_USER_REVIEWS_FAILURE'
>>>>>>> 59e47ea238ab881a79451ac59ca21b7813dccf67
};

const EditReviewActionsConstats = {
    EDIT_MY_REVIEWS: 'EDIT_MY_REVIEWS',
}

export {ProfileActionsConstants, EditReviewActionsConstats}