const UsersPageActionsConstants = {
    GET_USERS: 'GET_USERS',
    GET_REVIEWS: 'GET_REVIEWS',

    CHANGE_LAYOUT: 'CHANGE_LAYOUT',
    CHANGE_VISIBILITY_REVIEW: 'CHANGE_VISIBILITY_REVIEW',
    ON_SORT_CHANGE: 'ON_SORT_CHANGE',
    SELECT_REVIEW: 'SELECT_REVIEW',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',

    GET_REVIEW_SUCCESS: 'GET_REVIEW_SUCCESS',
    GET_REVIEW_FAILURE: 'GET_REVIEW_FAILURE',
<<<<<<< HEAD
    CHANGE_LAYOUT2: 'CHANGE_LAYOUT2',
    CHANGE_RATE: 'CHANGE_RATE',

=======
>>>>>>> 276e890bdef368d0d94ef616feaf0ac7083d5d68
};

export {UsersPageActionsConstants}
