const UsersPageActionsConstants = {
    GET_USERS: 'GET_USERS',
    GET_REVIEWS: 'GET_REVIEWS',

    CHANGE_LAYOUT: 'CHANGE_LAYOUT',
    CHANGE_VISIBILITY_REVIEW: 'CHANGE_VISIBILITY_REVIEW',
    ON_SORT_CHANGE: 'ON_SORT_CHANGE',
    SELECT_REVIEW: 'SELECT_REVIEW',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
    CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD',
    SEARCH_USERS: 'SEARCH_USERS',

    GET_REVIEW_SUCCESS: 'GET_REVIEW_SUCCESS',
    GET_REVIEW_FAILURE: 'GET_REVIEW_FAILURE',
    CHANGE_RATE: 'CHANGE_RATE',
    ON_SORT_CHANGE_RATING: 'ON_SORT_CHANGE_RATING',

};

export {UsersPageActionsConstants}
