const UsersPageActionsConstants = {
    ON_SORT_CHANGE: 'ON_SORT_CHANGE',
    GET_USERS: 'GET_USERS',
    GET_REVIEWS: 'GET_REVIEWS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
    CHANGE_LAYOUT: 'CHANGE_LAYOUT',
    CHANGE_VISIBILITY_USER: 'CHANGE_VISIBILITY_USER',
    CHANGE_VISIBILITY_REVIEW: 'CHANGE_VISIBILITY_REVIEW',
    SELECT_REVIEW: 'SELECT_REVIEW',
    CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',
    GET_REVIEW_SUCCESS: 'GET_REVIEW_SUCCESS',
    GET_REVIEW_FAILURE: 'GET_REVIEW_FAILURE',
    CHANGE_RATE: 'CHANGE_RATE'
};


export {UsersPageActionsConstants}