const RegisterActionsConstants = {
    SET_LOADING: 'SET_LOADING',
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    CHANGE_REGISTER_FIELD: 'CHANGE_REGISTER_FIELD'
};

export {RegisterActionsConstants}
